# Generated by Django 2.0 on 2018-09-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20180924_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='author',
            new_name='user',
        ),
    ]
