# Generated by Django 2.0 on 2018-09-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20180924_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='message',
            field=models.CharField(max_length=140, verbose_name='やること'),
        ),
    ]
